[workspace]
resolver = "2"
members = ["crates/ltc", "crates/cue", "crates/sink", "apps/chasefire-cli"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
license = "GPL-3.0-or-later"
repository = "https://github.com/mr-bolster/chasefire"
authors = ["Leo Bolster"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
